-- local present, gitlinker = pcall(require, "gitlinker")
--
-- if not present then
--   return
-- end
--
-- local options = {
--   opts = {
--     action_callback = nil,
--   },
--   mappings = nil,
-- }
--
-- gitlinker.setup(options)
